package com.garage.model;
// Generated May 24, 2019 10:38:21 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedNativeQueries;
import org.hibernate.annotations.NamedNativeQuery;

/**
 * Prenotation generated by hbm2java
 */

@NamedNativeQueries({
	
	@NamedNativeQuery(
			name = "availablePrenotationProcedure",
			query = "CALL availablePrenotation(:paramDate)",
			resultClass = Prenotation.class
			),
	@NamedNativeQuery(
			name = "prenSpecificVehicleProcedure",
			query = "CALL prenSpecificVehicle(:specificID)",
			resultClass = Prenotation.class
			),
	@NamedNativeQuery(
			name = "myVehiclePrenotationProcedure",
			query = "CALL myVehicleProcedure(:idutente)",
			resultClass = Prenotation.class
			),
		}) 
 
@Entity
@Table(name = "prenotation", catalog = "garage2")
public class Prenotation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;  
	
	private Integer idprenotation;
	private User user;
	private Vehicle vehicle;
	private Date rentstart;
	private Date rentend;

	public Prenotation() {
	}

	public Prenotation(User user, Vehicle vehicle) {
		this.user = user;
		this.vehicle = vehicle;
	}

	public Prenotation(User user, Vehicle vehicle, Date rentstart, Date rentend) {
		this.user = user;
		this.vehicle = vehicle;
		this.rentstart = rentstart;
		this.rentend = rentend;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idprenotation", unique = true, nullable = false)
	public Integer getIdprenotation() {
		return this.idprenotation;
	}

	public void setIdprenotation(Integer idprenotation) {
		this.idprenotation = idprenotation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_iduser", nullable = true)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_idvehicle", nullable = true)
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rentstart", length = 10, nullable = true)
	public Date getRentstart() {
		return this.rentstart;   
	}

	public void setRentstart(Date rentstart) {
		this.rentstart = rentstart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rentend", length = 10, nullable = true)
	public Date getRentend() {
		return this.rentend;
	}

	public void setRentend(Date rentend) {
		this.rentend = rentend;
	}

	@Override
	public String toString() {  
		return "Prenotation [idprenotation=" + idprenotation + ", user=" + user + ", vehicle=" + vehicle
				+ ", rentstart=" + rentstart + ", rentend=" + rentend + "]";
	}

}
