package com.garage.model;
// Generated May 24, 2019 10:38:21 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "garage2", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer iduser;
	private String firstname;
	private String lastname;
	private String username;
	private String password;
	private Set<Prenotation> prenotations = new HashSet<Prenotation>(0);

	public User() {
	}
	
	public User(String firstname, String lastname, String username, String password) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.username = username;
		this.password = password;
	}

	public User(String firstname, String lastname, String username, String password, Set<Prenotation> prenotations) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.username = username;
		this.password = password;
		this.prenotations = prenotations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iduser", unique = true, nullable = false)
	public Integer getIduser() {
		return this.iduser;
	}

	@Autowired(required = false)
	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	@Column(name = "firstname", nullable = true, length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	@Autowired(required = false)
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = true, length = 45)
	public String getLastname() {
		return this.lastname;
	}

	@Autowired(required = false)
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "username", unique = true, nullable = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	@Autowired(required = false)
	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = true, length = 45)
	public String getPassword() {
		return this.password;
	}

	@Autowired(required = false)
	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Prenotation> getPrenotations() {
		return this.prenotations;
	}

	public void setPrenotations(Set<Prenotation> prenotations) {
		this.prenotations = prenotations;
	}

	@Override
	public String toString() {
		return "User [iduser=" + iduser + ", firstname=" + firstname + ", lastname=" + lastname + ", username="
				+ username + ", password=" + password + ", prenotations=" + prenotations + "]";
	}

}
