package com.garage.model;
// Generated May 24, 2019 10:38:21 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * Vehicleinfo generated by hbm2java
 */

@Entity
@Table(name = "vehicleinfo", catalog = "garage2", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
public class Vehicleinfo implements java.io.Serializable {
 
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int vehicletype;
	private String description;
	private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

	public Vehicleinfo() {
	}

	public Vehicleinfo(int vehicletype, String description) {
		this.vehicletype = vehicletype;
		this.description = description;
	}

	public Vehicleinfo(int vehicletype, String description, Set<Vehicle> vehicles) {
		this.vehicletype = vehicletype;
		this.description = description;
		this.vehicles = vehicles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vehicletype", unique = true, nullable = false)
	public int getVehicletype() {
		return this.vehicletype;
	}

	@Autowired(required = false)
	public void setVehicletype(int vehicletype) {
		this.vehicletype = vehicletype;
	}
 
	@Column(name = "description", unique = true, nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	@Autowired(required = false)
	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleinfo")
	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	@Override
	public String toString() {
		return "Vehicleinfo [vehicletype=" + vehicletype + ", description=" + description + ", vehicles=" + vehicles
				+ "]";
	}

}
