package com.garage.model;
// Generated May 24, 2019 10:38:21 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "garage2", uniqueConstraints = @UniqueConstraint(columnNames = "licenseplate"))
public class Vehicle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idvehicle;
	private Vehicleinfo vehicleinfo;
	private String licenseplate;
	private String brand;
	private Set<Prenotation> prenotations = new HashSet<Prenotation>(0);

	public Vehicle() {
	}

	public Vehicle(Vehicleinfo vehicleinfo, String licenseplate, String brand) {
		this.vehicleinfo = vehicleinfo;
		this.licenseplate = licenseplate;
		this.brand = brand;
	}

	public Vehicle(Vehicleinfo vehicleinfo, String licenseplate, String brand, Set<Prenotation> prenotations) {
		this.vehicleinfo = vehicleinfo;
		this.licenseplate = licenseplate;
		this.brand = brand;
		this.prenotations = prenotations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idvehicle", unique = true, nullable = false)
	public Integer getIdvehicle() {
		return this.idvehicle;
	}

	public void setIdvehicle(Integer idvehicle) {
		this.idvehicle = idvehicle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_vehicletype", nullable = true)
	public Vehicleinfo getVehicleinfo() {
		return this.vehicleinfo;
	}

	public void setVehicleinfo(Vehicleinfo vehicleinfo) {
		this.vehicleinfo = vehicleinfo;
	}

	@Column(name = "licenseplate", unique = true, nullable = false, length = 45)
	public String getLicenseplate() {
		return this.licenseplate;
	}

	public void setLicenseplate(String licenseplate) {
		this.licenseplate = licenseplate;
	}

	@Column(name = "brand", nullable = false, length = 45)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicle")
	public Set<Prenotation> getPrenotations() {
		return this.prenotations;
	}

	public void setPrenotations(Set<Prenotation> prenotations) {
		this.prenotations = prenotations;
	}

	@Override
	public String toString() {
		return "Vehicle [idvehicle=" + idvehicle + ", vehicleinfo=" + vehicleinfo + ", licenseplate=" + licenseplate
				+ ", brand=" + brand + ", prenotations=" + prenotations + "]";
	}

}
